"""change Business backref

Revision ID: 0390db2d213f
Revises: 40b851cce946
Create Date: 2022-09-07 02:17:53.439246

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0390db2d213f'
down_revision = '40b851cce946'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('comment', sa.Column('post', sa.Integer(), nullable=True))
    op.drop_constraint('comment_post_id_fkey', 'comment', type_='foreignkey')
    op.create_foreign_key(None, 'comment', 'post', ['post'], ['id'], ondelete='CASCADE')
    op.drop_column('comment', 'post_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('comment', sa.Column('post_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'comment', type_='foreignkey')
    op.create_foreign_key('comment_post_id_fkey', 'comment', 'post', ['post_id'], ['id'], ondelete='CASCADE')
    op.drop_column('comment', 'post')
    # ### end Alembic commands ###
