"""Change nullablel

Revision ID: 40b851cce946
Revises: f487d90eb63e
Create Date: 2022-09-06 21:24:17.938455

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '40b851cce946'
down_revision = 'f487d90eb63e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('business', 'name',
               existing_type=sa.VARCHAR(length=150),
               nullable=True)
    op.alter_column('comment', 'text',
               existing_type=sa.VARCHAR(length=200),
               nullable=True)
    op.alter_column('comment', 'author',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('comment', 'post_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('like', 'author',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('like', 'post_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('post', 'author',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('post', 'business',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('post', 'business',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('post', 'author',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('like', 'post_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('like', 'author',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('comment', 'post_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('comment', 'author',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('comment', 'text',
               existing_type=sa.VARCHAR(length=200),
               nullable=False)
    op.alter_column('business', 'name',
               existing_type=sa.VARCHAR(length=150),
               nullable=False)
    # ### end Alembic commands ###
