"""backref

Revision ID: 74d88bce5878
Revises: 0390db2d213f
Create Date: 2022-09-07 11:36:56.584549

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '74d88bce5878'
down_revision = '0390db2d213f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('post', sa.Column('post_business', sa.Integer(), nullable=True))
    op.drop_constraint('post_business_fkey', 'post', type_='foreignkey')
    op.create_foreign_key(None, 'post', 'business', ['post_business'], ['id'], ondelete='CASCADE')
    op.drop_column('post', 'business')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('post', sa.Column('business', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'post', type_='foreignkey')
    op.create_foreign_key('post_business_fkey', 'post', 'business', ['business'], ['id'], ondelete='CASCADE')
    op.drop_column('post', 'post_business')
    # ### end Alembic commands ###
