"""change posts model to reference business name instead of id

Revision ID: ecd35a3e72c3
Revises: 74d88bce5878
Create Date: 2022-09-08 10:17:19.832928

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ecd35a3e72c3'
down_revision = '74d88bce5878'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('post_post_business_fkey', 'post', type_='foreignkey')
    op.create_foreign_key(None, 'post', 'business', ['post_business'], ['name'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'post', type_='foreignkey')
    op.create_foreign_key('post_post_business_fkey', 'post', 'business', ['post_business'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###
