"""Add Business Model

Revision ID: f487d90eb63e
Revises: 9c7a2913d079
Create Date: 2022-09-06 20:47:13.946810

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f487d90eb63e'
down_revision = '9c7a2913d079'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('post', sa.Column('business', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'post', 'business', ['business'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'post', type_='foreignkey')
    op.drop_column('post', 'business')
    # ### end Alembic commands ###
